CONTAINER OOceanEffectorValkaari
{
	NAME OOceanEffectorValkaari;
	
	INCLUDE Obaseeffector;
 	INCLUDE OceanDescription;
	INCLUDE Oedeformer_panel;

	HIDE OD_WAVE_HEIGHT;
    HIDE OD_DO_NORMALS;
    HIDE OD_DO_JACOBIAN;
	HIDE OD_CREATE_FOAM_TAGS;
    HIDE OD_JACOBMAP;
    HIDE OD_FOAMMAP;
    HIDE OD_JACOB_THRES;
    HIDE OD_FOAM_THRES;
    HIDE OD_PSEL_PARTICLES;
    HIDE OD_PSEL_THRES;
}
